INSERT INTO users(name, age) VALUES ("Oliver", 80);
INSERT INTO users(name, age) VALUES ("Jack", 22);
INSERT INTO users(name, age) VALUES ("George", 78);
INSERT INTO users(name, age) VALUES ("Noah", 53);
INSERT INTO users(name, age) VALUES ("Charlie", 75);
INSERT INTO users(name, age) VALUES ("Jacob", 82);
INSERT INTO users(name, age) VALUES ("Alfie", 24);
INSERT INTO users(name, age) VALUES ("Freddie", 73);
INSERT INTO users(name, age) VALUES ("Oscar", 59);
INSERT INTO users(name, age) VALUES ("Harry", 55);
INSERT INTO users(name, age) VALUES ("Olivia", 31);
INSERT INTO users(name, age) VALUES ("Amelia", 90);
INSERT INTO users(name, age) VALUES ("Isla", 76);
INSERT INTO users(name, age) VALUES ("Emily", 77);
INSERT INTO users(name, age) VALUES ("Ava", 89);
INSERT INTO users(name, age) VALUES ("Lily", 79);
INSERT INTO users(name, age) VALUES ("Mia", 27);
INSERT INTO users(name, age) VALUES ("Sophia", 49);
INSERT INTO users(name, age) VALUES ("Isabella", 51);
INSERT INTO users(name, age) VALUES ("Grace", 39);

INSERT INTO projects(title, category, funding_goal, start_date, end_date)
